<?php

$num1 =100;
$num2 =200;
    
$soma = $num1 +$num2;
if ($soma >= 200){
    echo "MAIOR QUE 200";
}else{
    echo "MENOR QUE 200";
}
echo "<br/> o resultado da soma é {$soma}";
?>
<html>
    <header>



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aula de Quarta</title>
</head>
<body>
    
</body>
</html>
/html>
<?php echo "<br/><br/> intervalo até 15;30"
</body>
</html>
